id: P6DB58D3A
initial_creation_type: input
source_metadata:
  title: Lochen Dharmaśrī Series
  language: bo
  description: 'Texts by and about Lochen Dharmaśrī (lo chen dhar+ma shrI, 1654–1717/18),
    the younger brother of Minling Terchen Gyurme Dorje and a major figure in the
    Nyingma tradition:'
  volume:
    2e4ba1527a7a4a9f8e7be918b304bd1e:
      title: A Brief Explanation of the Ten Virtues and Eighteen Elements
      parent: Abhidharma
    ea0953e0a5b54af0a0509c529b001026:
      title: Prayer for the Long Life of Lochen Ngawang Chöpal
      parent: Long Life Prayers
created_at: '2022-03-01T00:38:37.801317'
last_modified_at: '2022-03-01T00:38:37.801320'
